apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators-redhat
spec:
  channel: stable 
  name: jaeger-product 
  source: ossm-catalog
  sourceNamespace: openshift-marketplace
