apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators-redhat
spec:
  channel: "1.0"
  name: servicemeshoperator
  source: ossm-catalog
  sourceNamespace: openshift-marketplace
